### ISSUE TITLE
synthcore library

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/msvr#25]
@grrrwaaa It looks great. Cost is $20. Could we get a license for the lab?

**Comment by grrrwaaa** [comment]
I'll contact Ernest and see if we can request a license for the project. In the meantime, a free, older version is available here: https://www.yofiel.com/software/mac-and-pc-apps/synthcore2

**Comment by grrrwaaa** [comment]
Ah whoops -- mixed up the synth app and the library -- ignore that link above. But looking back through the forums, there was a beta here that we could look at while I wait to hear from Ernest: https://cycling74.com/forums/sharing-synthcore-gen-library

And there's more here: https://www.yofiel.com/software/cycling-74-patches/

**Comment by michaelpalumbo** [comment]
On it! Thanks!
