### ISSUE TITLE
deferlow not instantiating in max patch

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/msvr#50]
There are six deferlow objects in my patch which also has a node.script running. The deferlow objects are not instantiating on load of the patch nor if I add one in edit mode. I'm only able to add a deferlow object if doing so in a new patcher, regardless whether my problematic patch is open or not. 

note also that this problem occurred only after adding the 6th deferlow after having 5 for nearly a year and no problems with this object.

**Comment by michaelpalumbo** [comment]
https://cycling74.com/forums/deferlow-no-such-object

**Comment by michaelpalumbo** [comment]
am able to successfully load the patch with the deferlow objects if i first load a blank patcher and add deferlow...

**Comment by michaelpalumbo** [comment]
help from vichug in themax forums, may have traced the issue to several js files named deferlow. working now to rename them.

**Comment by michaelpalumbo** [comment]
aha! this solved it. renamed deferlow.js to deferlowScript.js

suggestrefactoring the deferlow objects at some point.

**Comment by grrrwaaa** [comment]
Ah yes, Max is old enough software that it remembers pre-OSX days when file extensions were a foreign concept, and thus ignores them sometimes, leading to weird bugs when naming a max patcher or js file the same as an external...
