### ISSUE TITLE
cable interactions

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/msvr#66]
1. creating a new cable and letting go of it it should delete (because it's more of a 'nah, i don't want to do this')

2. but keep the dangling cable when disconnecting one at one given patch point that was already connected between two patch points

**Comment by Zodsmar** [comment]
To keep it simple, Graham and I decided for stability reasons to make dangling cables not a thing. This way they do not exist in the graph. (Dangling cables are disabled for now until after the stability milestone) @michaelpalumbo
